"""Modify relationship

Revision ID: 2a260ffb635c
Revises: d5150befec43
Create Date: 2024-05-30 13:10:26.134848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a260ffb635c'
down_revision: Union[str, None] = 'd5150befec43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scores', 'students', ['student_id'], ['id'])
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.drop_constraint('students_score_id_fkey', 'students', type_='foreignkey')
    op.drop_column('students', 'score_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('score_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('students_score_id_fkey', 'students', 'scores', ['score_id'], ['id'])
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_column('scores', 'student_id')
    # ### end Alembic commands ###
