"""Remove lazy=dynamic from Student model

Revision ID: 68f36ceeaaf9
Revises: 2a260ffb635c
Create Date: 2024-05-30 14:39:45.917867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f36ceeaaf9'
down_revision: Union[str, None] = '2a260ffb635c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
