"""Add new fields

Revision ID: d5150befec43
Revises: 159493be188b
Create Date: 2024-05-30 12:06:30.221623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5150befec43'
down_revision: Union[str, None] = '159493be188b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('scores', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('students', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('students', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'updated_at')
    op.drop_column('students', 'created_at')
    op.drop_column('scores', 'updated_at')
    op.drop_column('scores', 'created_at')
    # ### end Alembic commands ###
